### ISSUE TITLE
Incomplete login attempt

### ISSUE THREAD

**Issue by sahilkundu** [ShivangKakkar/StringSessionBot#9]
I am getting this error when i am using this repo in Kali linux.

Dear ####,
Telegram blocked an attempt to log into your account from a new device on dd/mm/yyyy at hh:min:sec UTC.
 Device: fileuploader, Pyrogram version, CPython version, Android, Linux version
Location: Location from where login attempted by Bot

Nobody gained access to your chats because the login was not completed. The code was entered correctly, but sign in was not allowed, because this code was previously shared by your account.

Please don't share login codes with others, because they allow anyone to log in to your account and access your chats.
![error](https://github.com/ShivangKakkar/StringSessionBot/assets/71582663/1521fdeb-4a5d-4956-90a1-b1d2cac5cd0d)

**Comment by ShivangKakkar** [comment]
I think you might be using the bot with the same account that needs a string session. If I'm right, you might be sending the code let's say `12345` directly as `12345`. This is in violation with Telegram Guidelines as you can't share the code on Telegram. There are 2 solutions:

1. Send code with spaces: `1 2 3 4 5` instead of `12345`.

2. Use another account to interact with the bot.

**Comment by Snehashish06** [comment]
@sahilkundu You should try enabling **2 step verification** if this problem remains after what @ShivangKakkar told you to do.

**Comment by sahilkundu** [comment]
> I think you might be using the bot with the same account that needs a string session. If I'm right, you might be sending the code let's say `12345` directly as `12345`. This is in violation with Telegram Guidelines as you can't share the code on Telegram. There are 2 solutions:
> 
> 1. Send code with spaces: `1 2 3 4 5` instead of `12345`.
> 2. Use another account to interact with the bot.

Yes this working.
Closed
